### ISSUE TITLE
Drag Pin in Map - iOS

### ISSUE THREAD

**Issue by andreluiz1987** [TorbenK/TK.CustomMap#159]
Hi.
I do not know if this is just happening to me but when I drag the pin to another map location it is duplicated and the application is closed. Only for iOS.
![map-3](https://cloud.githubusercontent.com/assets/4265196/21328952/671ee000-c61d-11e6-953d-d9508b3e091e.png)

**Comment by jfversluis** [comment]
It seems to work fine in the sample app. Do you have any code associated on the `DragEnd` which can cause an unhandled Exception?

**Comment by andreluiz1987** [comment]
I dont know Pins.Clear(); not work in my class. I created other method specific to iOS and now its works.

**Comment by feliperugai** [comment]
Hi there, I'm having the same issue @andreluiz1987! What did you do to make it work?

I need to draw a polygon everytime that the user clicks on the map. And when it drags any pin, it must "repaint" the polygon.

My method works perfectly in Android, but in iOS I get double pins and crashes.
**Obs:** I'm using Custom Pins and not Pins.
`    

        public void AtualizarPoligono()
        {
            if (!CustomPins.Any()) return;  var lstPoligonos = new List<TKPolygon>
            {
                new TKPolygon
                {
                    StrokeColor = Color.Green,
                    StrokeWidth = 1f,
                    Color = Color.Red,
                    Coordinates = new List<Position>()
                }
            };

            foreach (var pin in CustomPins)
            {
                lstPoligonos[0].Coordinates.Add(pin.Position);
            }

            Polygons = lstPoligonos;
        }`

Do you guys have any clues of what could be causing this issue?

**Comment by TorbenK** [comment]
If someone is able to share a repro project I will look at it. I am not able to reproduce this.

**Comment by feliperugai** [comment]
Hi TorbenK!
Thanks for replying btw.
I'm not connected to a Mac right now, but I extracted my classes and page to a new project and ran it on Android just to make sure it was running ok.
I couldn't upload here because the project is 10M>

[TKCustom.Map.iOSBug](https://drive.google.com/file/d/0B7oOTsv_kdjzQU8tTkVsb18xWnc/view?usp=sharing)

**Edit** In this project I forgot to add
```
    FormsMaps.Init();
    TKCustomMapRenderer.InitMapRenderer();
```
Just to make it clear, I'm attaching a video of the bug aswell, right now I'm uploading it. When its done I'll post here.

Thank you!!.

**Comment by feliperugai** [comment]
Here you go:

[TKCustomMapsiOS.mp4](https://drive.google.com/file/d/0B7oOTsv_kdjzUzUwNmdldlM4R00/view?usp=sharing)

**Comment by TorbenK** [comment]
I just had a quick look. Besides the problem, you should really think about moving to `ObservableCollection` instead of re-creating every list from scratch over and over again.

Anyway, even if it's bad, it should work as far as I see. Thanks for providing the sample, I will take a deeper look at it.

**Comment by feliperugai** [comment]
> I just had a quick look. Besides the problem, you should really think about moving to ObservableCollection instead of re-creating every list from scratch over and over again.

You are absolutely right. 
Thanks for taking a deeper look at it. I'll wait for your concerns.

**Comment by TorbenK** [comment]
Sorry, took some time. Turned out that I were setting wrong observers using the KVO. I pushed a fix for this. I will release 1.5.1 soon including this.

**Comment by feliperugai** [comment]
Nice @TorbenK!
Do you have any clue about when you are going to realease 1.5.1?

**Comment by TorbenK** [comment]
1.5.1

**Comment by feliperugai** [comment]
@TorbenK 
Is there any modifications I need to apply?
I just updated and tested on iOS and it's still not updating the polygon and crashing afterwards.
I got this error:

````
Unhandled Exception:



Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <MKMapAnnotationManager 0x1d244070> for the key path "coordinate" from <TK_CustomMap_iOSUnified_TKCustomMapAnnotation 0x1e1a6720> because it is not registered as an observer.
```

Native stack trace:

	0   CoreFoundation                      0x238a1b23 <redacted> + 150

	1   libobjc.A.dylib                     0x2305edff objc_exception_throw + 38

	2   CoreFoundation                      0x238a1a51 <redacted> + 0

	3   Foundation                          0x24021955 <redacted> + 588

	4   Foundation                          0x2402133b <redacted> + 158

	5   MapKit                              0x2cbb352b <redacted> + 258

	6   MapKit                              0x2cc2b30d <redacted> + 140

	7   MapKit                              0x2cbca4b9 <redacted> + 212

	8   MyProject.iOS            0x00de49cc wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_IntPtr_intptr_intptr_intptr + 108

	9   MyProject.iOS            0x00d9ef68 MapKit_MKMapView_RemoveAnnotations_MapKit_IMKAnnotation__ + 88

	10  MyProject.iOS            0x0170ab48 TK_CustomMap_iOSUnified_TKCustomMapRenderer_UpdatePins_bool + 264

	11  MyProject.iOS            0x01706214 TK_CustomMap_iOSUnified_TKCustomMapRenderer_OnMapPropertyChanged_object_System_ComponentModel_PropertyChangedEventArgs + 300

	12  MyProject.iOS            0x008ffe48 wrapper_delegate_invoke__Module_invoke_void_object_PropertyChangedEventArgs_object_System_ComponentModel_PropertyChangedEventArgs + 232

	13  MyProject.iOS            0x00493bac Xamarin_Forms_BindableObject_OnPropertyChanged_string + 272

	14  MyProject.iOS            0x005b2824 Xamarin_Forms_Element_OnPropertyChanged_string + 140

	15  MyProject.iOS            0x01006bf8 TK_CustomMap_TKCustomMap_OnPropertyChanged_string + 120

	16  MyProject.iOS            0x0049884c Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool + 1708

	17  MyProject.iOS            0x004966b4 Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags + 2508

	18  MyProject.iOS            0x0049816c Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool + 1028

	19  MyProject.iOS            0x0049342c Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object + 148

	20  MyProject.iOS            0x01003d44 TK_CustomMap_TKCustomMap_set_CustomPins_System_Collections_Generic_IEnumerable_1_TK_CustomMap_TKCustomMapPin + 136

	21  MyProject.iOS            0x00f52a84 BNB_CapturaGeodesica_CapturaDeGlebasManual_AdicionarPin_Xamarin_Forms_Maps_Position + 860

	22  MyProject.iOS            0x00f526a4 BNB_CapturaGeodesica_CapturaDeGlebasManual_AoClicarNoMapa_object_TK_CustomMap_TKGenericEventArgs_1_Xamarin_Forms_Maps_Position + 212

	23  MyProject.iOS            0x010078b8 TK_CustomMap_TKCustomMap_OnMapClicked_Xamarin_Forms_Maps_Position + 328

	24  MyProject.iOS            0x01008b60 TK_CustomMap_TKCustomMap_TK_CustomMap_Interfaces_IMapFunctions_RaiseMapClicked_Xamarin_Forms_Maps_Position + 196

	25  MyProject.iOS            0x01709750 TK_CustomMap_iOSUnified_TKCustomMapRenderer_OnMapClicked_UIKit_UITapGestureRecognizer + 3360

	26  MyProject.iOS            0x00d84a1c UIKit_UITapGestureRecognizer_Callback_Activated_UIKit_UITapGestureRecognizer + 52

	27  MyProject.iOS            0x003e69f8 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256

	28  MyProject.iOS            0x0009c493 mono_jit_runtime_invoke + 1650

	29  MyProject.iOS            0x000e4f9d do_runtime_invoke + 78

	30  MyProject.iOS            0x000e4f33 mono_runtime_invoke + 138

	31  MyProject.iOS            0x01775457 _ZL32native_to_managed_trampoline_106P11objc_objectP13objc_selectorPP11_MonoMethodP22UITapGestureRecognizerPKcS9_S9_ + 348

	32  MyProject.iOS            0x017752f7 -[__UITapGestureRecognizer target:] + 80

	33  UIKit                               0x283ea81b <redacted> + 142

	34  UIKit                               0x28022a53 <redacted> + 170

	35  UIKit                               0x27eb2e95 <redacted> + 1004

	36  UIKit                               0x283ebb7f <redacted> + 62

	37  UIKit                               0x27e736d7 <redacted> + 298

	38  UIKit                               0x27e6fc49 <redacted> + 2920

	39  CoreFoundation                      0x238632b1 <redacted> + 20

	40  CoreFoundation                      0x238615a7 <redacted> + 282

	41  CoreFoundation                      0x238619e5 <redacted> + 972

	42  CoreFoundation                      0x237b01c9 CFRunLoopRunSpecific + 516

	43  CoreFoundation                      0x237affbd CFRunLoopRunInMode + 108

	44  GraphicsServices                    0x24dccaf9 GSEventRunModal + 160

	45  UIKit                               0x27ee9435 UIApplicationMain + 144

	46  MyProject.iOS            0x00de1a64 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 272

	47  MyProject.iOS            0x00d7e714 UIKit_UIApplication_Main_string___intptr_intptr + 52

	48  MyProject.iOS            0x00d7e6d4 UIKit_UIApplication_Main_string___string_string + 204

	49  MyProject.iOS            0x0015ce00 BNB_CapturaGeodesica_iOS_Application_Main_string__ + 152

	50  MyProject.iOS            0x003e69f8 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256

	51  MyProject.iOS            0x0009c493 mono_jit_runtime_invoke + 1650

	52  MyProject.iOS            0x000e4f9d do_runtime_invoke + 78

	53  MyProject.iOS            0x000e67b5 mono_runtime_exec_main + 608

	54  MyProject.iOS            0x000e64a3 mono_runtime_run_main + 630

	55  MyProject.iOS            0x0008ae7f mono_jit_exec + 162

	56  MyProject.iOS            0x0015ac54 xamarin_main + 2508

	57  MyProject.iOS            0x01780bf3 main + 112

	58  libdyld.dylib                       0x2345c873 <redacted> + 2
`

**Comment by TorbenK** [comment]
I'm sorry, the error is still happening when deploying on a device. The fix was only tested on Simulator.

Unfortunately I'm currently too busy to look at it. I will do asap. Sorry.

**Comment by feliperugai** [comment]
@TorbenK please don't apologize! Your project is saving a lot of my time! I must apologize for being so inconvenient. I tried fixing it by myself but without any success. Thanks again!

**Comment by feliperugai** [comment]
Hi guys, I'm trying hard to find a fix for this. After some time I found that the crashes happens in `line 523` of `TKCustomMapRenderer.cs`, on the `UpdatePins `function.

```
private void UpdatePins(bool firstUpdate = true)
{
     this.Map.RemoveAnnotations(this.Map.Annotations); // The crash is here
...
}
```
I'm still looking into a solution, just posting it here in case someone that knows how iOS works want to help me. I'm not familiar with it.

**Comment by TorbenK** [comment]
@felrugai 

Sorry for the delay, I am extremly busy at the moment and have no time to look at it. I will do asap.

**Comment by JoseClua** [comment]
Hi I am also having this issue. It happens just in a real device. In my case I am using iphone 5 with IOS 10.3.

This is my scenario:

In my app the user can only have one pin at a time.

So when he tries to add a second pin, instead of displaying Add Pin, it says Move Pin.

When he taps in Move Pin I do the following:

    this._pins.Clear();

    var pin = new TKCustomMapPin
    {
        Position = position,
        Title = string.Format("Pin {0}, {1}", position.Latitude,
        position.Longitude),
        ShowCallout = true,
        IsDraggable = true
    };
    this._pins.Add(pin);

This works fine in the emulators. But in the real device, only when the user had previously dragged the pin, it doesn't get cleared. So when he Moves the pin, he can still see the previous one, he can see two pins! After that the app crashes trying to do anything.

It seems like a bug in the Clear method that doesn't work when the pin got dragged before. 

Please let me know if there is a work around for this issue, ok?

Besides that the API is working great and the business users are loving it.

Thanks

**Comment by pamela032709** [comment]
Hi , did anyone have found a solution so far . Im hesitant to do any major change since this is working perfectly on android.
