### ISSUE TITLE
On Navigate Back after MapView_PinDragEnd; is called. ( iOS ) 1.5.1

### ISSUE THREAD

**Issue by masodev** [TorbenK/TK.CustomMap#177]
[0:] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <MKMapAnnotationManager 0x174325640> for the key path "coordinate" from <TK_CustomMap_iOSUnified_TKCustomMapAnnotation 0x175a2b0c0> because it is not registered as an observer.

After I move the Pin and I try to navigate away application crashes only on iOS

**Comment by TorbenK** [comment]
This is happening on the current 1.5.1? I thought I fixed that

**Comment by masodev** [comment]
@TorbenK Yes indeed I was waiting for the change since I saw you mention an update coming soon and tried it out as soon as the updated nuget was released, I tried cleaning and rebuilding my project but still the same behaviour. Anything else I should try?

**Comment by TorbenK** [comment]
I did a quick test yesterday dragging a pin and pushing a new page. I couldn't reproduce it. Is it possible that you provide a little repro project for me?

**Comment by Sagariouz** [comment]
[SampleDragPinError.zip](https://github.com/TorbenK/TK.CustomMap/files/741753/SampleDragPinError.zip)

Thanx for the help and quick responses - I have attached a repo from a previous user where he swaps out the map page, but with my added scenario where the map is removed from the container - both scenarios is just a quick way to reproduce the bug.

**Comment by TorbenK** [comment]
Still not able to reproduce it with the sample project...

**Comment by Sagariouz** [comment]
Even after dragging the pin? It works if you don't move the pin, but fails if you remove the map/change page after moving the pin - the two buttons.
On which ios version/device/simulator are you testing, then I'll make sure of my facts.
Thanx again..

**Comment by masodev** [comment]
@TorbenK For me it as is reproduced only after the Pin is dragged and I try to navigate back (exactly as described by @Sagariouz) , if the pin is not dragged the application does not crash, I have tried debugging on an physical iPhone 5s with iOS 10.2.1 and an physical iPhone 7 with iOS 10.2.1.

**Comment by TorbenK** [comment]
Dragged pin and pushed and popped the page.

Tested on simulator 10.2.

**Comment by masodev** [comment]
@TorbenK I tried replicating on 10.2 simulator and I cannot replicate. I can only replicate on  physical devices.

**Comment by masodev** [comment]
@TorbenK Any updates?

**Comment by TorbenK** [comment]
@masodev 

Sorry for the delay. see #185.

**Comment by masodev** [comment]
Thanks! @TorbenK 

@Sagariouz FYI

**Comment by masodev** [comment]
@TorbenK Any ideas when the fix will be included in nuget update?

**Comment by TorbenK** [comment]
There were still issues. I hope with the latest commit we have it stable now. I don't really know when I will create the new package, but I think the lates will be on Monday.

**Comment by TorbenK** [comment]
Sorry for the long delay, there is a pre release which should fix your issue.

**Comment by masodev** [comment]
@TorbenK Issue resolved, tested on Physical devices. Thank you!
