### ISSUE TITLE
pin.image not working in android only after xamarin upgrade

### ISSUE THREAD

**Issue by abdulbasitnawab** [TorbenK/TK.CustomMap#223]
Hi
After upgrading the xamarin/visual studio when I run my application in iOS it works perfectly fine. While in android it is throwing error
System.Collections.ListDictionaryInternal An item with the same key has already been added.
After investing a lot of time to narrow down the issue I found that I was using images for pins. When I comment the code for using pin.Image and add color instead of image the app started working in android without throwing any exception, But  I need the marker as image not colored.
Any help in this regard will be highly appreciated.

**Comment by abdulbasitnawab** [comment]
Hi
After a lot of search and hit and try, I found that this issue is due to xamarin.forms.maps version 2.3.4.247. I downgraded to 2.3.3.180 the issue is resolved.

**Comment by Shashidhar014** [comment]
Downgrading to 2.3.3.180 worked for me

**Comment by garie** [comment]
Downgrading is not a valid fix for this issue, it is a temporary workaround. In the future, please don't close issues like this.
I upgraded to 2.3.4.267 today and the issue seems to have stopped occurring but I will update if I see it happen again.

**Comment by garie** [comment]
Never mind, it is still broken with XF 2.3.4.267. @TorbenK can you please reopen this.

**Comment by garie** [comment]
The bug does not occur in the development branch of TK.CustomMap with packages updated.

**Comment by eltonmrk** [comment]
It's still not visible on the latest version 2.0.1
